# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bundler'
require "bubble-wrap/location"
Bundler.setup
Bundler.require :default
BW.require '/app/main_controller.rb'

Motion::Project::App.setup do |app|
  app.codesign_certificate = "iPhone Developer: Ramses Reyes Contreras (94Q7H97XUA)"
  app.name = 'ZenDriving'
  app.frameworks += ['CoreLocation', 'MapKit']
end
