# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bundler'
require "bubble-wrap/location"
require "bubble-wrap/core"
Bundler.setup
Bundler.require :default
BW.require '/app/main_controller.rb'

Motion::Project::App.setup do |app|
  app.name = 'ZenDriving'
  app.frameworks += ['CoreLocation', 'MapKit']
  app.interface_orientations = [:landscape_left, :landscape_right]
  app.resources_dir = "resources"
end
